//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreResource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Font.
        /// </summary>
        internal static string ArabicFont_Text {
            get {
                return ResourceManager.GetString("ArabicFont.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back_Label {
            get {
                return ResourceManager.GetString("Back.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Font Size.
        /// </summary>
        internal static string DecreaseFontSize_Label {
            get {
                return ResourceManager.GetString("DecreaseFontSize.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Font Size.
        /// </summary>
        internal static string DefaultFontSize_Label {
            get {
                return ResourceManager.GetString("DefaultFontSize.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qur&apos;an with its Arabic, transliteration and translation word by word and verse by verse for learning, studying, research, memorization, reflection and mastery of tajweed..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran Word By Word.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Font Size.
        /// </summary>
        internal static string IncreaseFontSize_Label {
            get {
                return ResourceManager.GetString("IncreaseFontSize.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Text Font.
        /// </summary>
        internal static string OtherTextFont_Text {
            get {
                return ResourceManager.GetString("OtherTextFont.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render.
        /// </summary>
        internal static string Render_Label {
            get {
                return ResourceManager.GetString("Render.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Label {
            get {
                return ResourceManager.GetString("Settings.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Translation.
        /// </summary>
        internal static string ShowTranslation_Text {
            get {
                return ResourceManager.GetString("ShowTranslation.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Transliteration.
        /// </summary>
        internal static string ShowTransliteration_Text {
            get {
                return ResourceManager.GetString("ShowTransliteration.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Word By Word.
        /// </summary>
        internal static string ShowWordByWord_Text {
            get {
                return ResourceManager.GetString("ShowWordByWord.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size_Text {
            get {
                return ResourceManager.GetString("Size.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Recitation Rule Coloring.
        /// </summary>
        internal static string UseRecitationRuleColoring_Text {
            get {
                return ResourceManager.GetString("UseRecitationRuleColoring.Text", resourceCulture);
            }
        }
    }
}
