//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoreResource.StoreResources", typeof(StoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AdditionalLicenseTerms {
            get {
                return ResourceManager.GetString("AdditionalLicenseTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran Word by Word Translation.
        /// </summary>
        internal static string AppFeature1 {
            get {
                return ResourceManager.GetString("AppFeature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transliteration.
        /// </summary>
        internal static string AppFeature2 {
            get {
                return ResourceManager.GetString("AppFeature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string AppFeature3 {
            get {
                return ResourceManager.GetString("AppFeature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verse by Verse.
        /// </summary>
        internal static string AppFeature4 {
            get {
                return ResourceManager.GetString("AppFeature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word by Word.
        /// </summary>
        internal static string AppFeature5 {
            get {
                return ResourceManager.GetString("AppFeature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran.
        /// </summary>
        internal static string AppFeature6 {
            get {
                return ResourceManager.GetString("AppFeature6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran viewer.
        /// </summary>
        internal static string AppFeature7 {
            get {
                return ResourceManager.GetString("AppFeature7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tajweed.
        /// </summary>
        internal static string AppFeature8 {
            get {
                return ResourceManager.GetString("AppFeature8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) GMorseCode.
        /// </summary>
        internal static string CopyrightTrademarkInfo {
            get {
                return ResourceManager.GetString("CopyrightTrademarkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qur&apos;an with its Arabic, transliteration and translation word by word and verse by verse for learning, studying, research, memorization, reflection and mastery of tajweed..
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Quran viewer..
        /// </summary>
        internal static string DesktopScreenshotDescription1 {
            get {
                return ResourceManager.GetString("DesktopScreenshotDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran.
        /// </summary>
        internal static string Keyword1 {
            get {
                return ResourceManager.GetString("Keyword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        internal static string Keyword2 {
            get {
                return ResourceManager.GetString("Keyword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transliteration.
        /// </summary>
        internal static string Keyword3 {
            get {
                return ResourceManager.GetString("Keyword3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string Keyword4 {
            get {
                return ResourceManager.GetString("Keyword4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qur&apos;an.
        /// </summary>
        internal static string Keyword5 {
            get {
                return ResourceManager.GetString("Keyword5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koran.
        /// </summary>
        internal static string Keyword6 {
            get {
                return ResourceManager.GetString("Keyword6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al-Quran.
        /// </summary>
        internal static string Keyword7 {
            get {
                return ResourceManager.GetString("Keyword7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Quran viewer..
        /// </summary>
        internal static string MobileScreenshotDescription1 {
            get {
                return ResourceManager.GetString("MobileScreenshotDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Version..
        /// </summary>
        internal static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gregory.morse@live.com.
        /// </summary>
        internal static string SupportContactInfo {
            get {
                return ResourceManager.GetString("SupportContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.islamsource.info.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
