#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IslamSourceQuranViewer.Xam.Droid.Resource", IsApplication=true)]

namespace IslamSourceQuranViewer.Xam.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::IslamSourceQuranViewer.Xam.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f030000
			public const int de_aburida = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int de_bubenheim = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int de_khoury = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int de_w4w = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int de_w4w_corpus = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int de_zaidan = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int en_ahmedali = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int en_ahmedraza = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int en_arberry = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int en_asad = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int en_daryabadi = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int en_hilali = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int en_itani = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int en_maududi = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int en_maulana_ali = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int en_mubarakpuri = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int en_pickthall = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int en_qarai = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int en_qaribullah = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int en_sahih = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int en_sarwar = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int en_shakir = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int en_transliteration = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int en_w4w = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int en_w4w_corpus = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int en_w4w_qurandev = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int en_w4w_shehnazshaikh = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int en_wahiduddin = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int en_yusufali = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int es_asad = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int es_bornez = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int es_cortes = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int es_garcia = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int es_w4w = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int es_w4w_corpus = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int fr_hamidullah = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int fr_w4w = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int fr_w4w_corpus = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int hu_halima = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int hu_w4w = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int hu_w4w_corpus = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int id_indonesian = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int id_jalalayn = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int id_muntakhab = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int id_w4w = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int id_w4w_terjemah = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int ms_basmeih = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int ms_w4w = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int ms_w4w_terjemah = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int ru_abuadel = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int ru_krachkovsky = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int ru_kuliev = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int ru_kuliev_alsaadi = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int ru_muntahab = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int ru_osmanov = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int ru_porokhova = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int ru_sablukov = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int ru_w4w = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int ru_w4w_corpus = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int ur_ahmedali = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int ur_jalandhry = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int ur_jawadi = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int ur_junagarhi = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int ur_kanzuliman = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int ur_maududi = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int ur_najafi = 2130903105;
			
			// aapt resource value: 0x7f030042
			public const int ur_qadri = 2130903106;
			
			// aapt resource value: 0x7f030043
			public const int ur_w4w = 2130903107;
			
			// aapt resource value: 0x7f030044
			public const int ur_w4w_hafiznazarmuhammad = 2130903108;
			
			// aapt resource value: 0x7f030045
			public const int zh_Hans_w4w = 2130903109;
			
			// aapt resource value: 0x7f030046
			public const int zh_Hans_w4w_corpus = 2130903110;
			
			// aapt resource value: 0x7f030047
			public const int zh_Hant_w4w = 2130903111;
			
			// aapt resource value: 0x7f030048
			public const int zh_Hant_w4w_corpus = 2130903112;
			
			// aapt resource value: 0x7f030049
			public const int zh_jian = 2130903113;
			
			// aapt resource value: 0x7f03004a
			public const int zh_majian = 2130903114;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
	}
}
#pragma warning restore 1591
