'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("XMLRender.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account successfully activated..
    '''</summary>
    Friend Shared ReadOnly Property Acct_AccountActivateSuccess() As String
        Get
            Return ResourceManager.GetString("Acct_AccountActivateSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account already activated..
    '''</summary>
    Friend Shared ReadOnly Property Acct_AccountAlreadyActivated() As String
        Get
            Return ResourceManager.GetString("Acct_AccountAlreadyActivated", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account successfully deleted..
    '''</summary>
    Friend Shared ReadOnly Property Acct_AccountDeleteSuccess() As String
        Get
            Return ResourceManager.GetString("Acct_AccountDeleteSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Account not yet activated please check your email first or request an additional activation code..
    '''</summary>
    Friend Shared ReadOnly Property Acct_AccountNotActivated() As String
        Get
            Return ResourceManager.GetString("Acct_AccountNotActivated", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Activate Account.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ActivateAccount() As String
        Get
            Return ResourceManager.GetString("Acct_ActivateAccount", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This e-mail is requesting activation of your {0} account: {1}.  Please use the following link: {2} or by proceeding to the page {3} and entering your username and the following activation code: {4}.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ActivationAccountBody() As String
        Get
            Return ResourceManager.GetString("Acct_ActivationAccountBody", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Activation for account at {0}.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ActivationAccountSubject() As String
        Get
            Return ResourceManager.GetString("Acct_ActivationAccountSubject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Activation Code.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ActivationCode() As String
        Get
            Return ResourceManager.GetString("Acct_ActivationCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to E-mail address not in a valid format..
    '''</summary>
    Friend Shared ReadOnly Property Acct_BadEmailFormat() As String
        Get
            Return ResourceManager.GetString("Acct_BadEmailFormat", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you certain?.
    '''</summary>
    Friend Shared ReadOnly Property Acct_Certain() As String
        Get
            Return ResourceManager.GetString("Acct_Certain", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Certificate.
    '''</summary>
    Friend Shared ReadOnly Property Acct_Certificate() As String
        Get
            Return ResourceManager.GetString("Acct_Certificate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Install Certificate.
    '''</summary>
    Friend Shared ReadOnly Property Acct_CertInstall() As String
        Get
            Return ResourceManager.GetString("Acct_CertInstall", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Install Intermediate Certificate.
    '''</summary>
    Friend Shared ReadOnly Property Acct_CertInstallIntermed() As String
        Get
            Return ResourceManager.GetString("Acct_CertInstallIntermed", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Certificate Request.
    '''</summary>
    Friend Shared ReadOnly Property Acct_CertRequest() As String
        Get
            Return ResourceManager.GetString("Acct_CertRequest", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change E-mail Address.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ChangeEmailAddress() As String
        Get
            Return ResourceManager.GetString("Acct_ChangeEmailAddress", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change Password.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ChangePassword() As String
        Get
            Return ResourceManager.GetString("Acct_ChangePassword", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Change Username.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ChangeUsername() As String
        Get
            Return ResourceManager.GetString("Acct_ChangeUsername", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Activation sent to address provided.  Please check your e-mail to activate your account which will complete your registration..
    '''</summary>
    Friend Shared ReadOnly Property Acct_CheckEmailNotice() As String
        Get
            Return ResourceManager.GetString("Acct_CheckEmailNotice", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Cleanup Stale.
    '''</summary>
    Friend Shared ReadOnly Property Acct_CleanupStale() As String
        Get
            Return ResourceManager.GetString("Acct_CleanupStale", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Clear Cache.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ClearCache() As String
        Get
            Return ResourceManager.GetString("Acct_ClearCache", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Clear Disk Cache.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ClearDiskCache() As String
        Get
            Return ResourceManager.GetString("Acct_ClearDiskCache", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Confirm E-mail Address.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ConfirmEmailAddress() As String
        Get
            Return ResourceManager.GetString("Acct_ConfirmEmailAddress", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Confirm Password.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ConfirmPassword() As String
        Get
            Return ResourceManager.GetString("Acct_ConfirmPassword", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Control Panel.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ControlPanel() As String
        Get
            Return ResourceManager.GetString("Acct_ControlPanel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Create Database.
    '''</summary>
    Friend Shared ReadOnly Property Acct_CreateDatabase() As String
        Get
            Return ResourceManager.GetString("Acct_CreateDatabase", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Current User.
    '''</summary>
    Friend Shared ReadOnly Property Acct_CurrentUser() As String
        Get
            Return ResourceManager.GetString("Acct_CurrentUser", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete Account.
    '''</summary>
    Friend Shared ReadOnly Property Acct_DeleteAccount() As String
        Get
            Return ResourceManager.GetString("Acct_DeleteAccount", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Delete Certificate Request.
    '''</summary>
    Friend Shared ReadOnly Property Acct_DeleteCertRequest() As String
        Get
            Return ResourceManager.GetString("Acct_DeleteCertRequest", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Dot Net Version.
    '''</summary>
    Friend Shared ReadOnly Property Acct_DotNetVersion() As String
        Get
            Return ResourceManager.GetString("Acct_DotNetVersion", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Download {0}.
    '''</summary>
    Friend Shared ReadOnly Property Acct_Download() As String
        Get
            Return ResourceManager.GetString("Acct_Download", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to User with this name already exists please choose another..
    '''</summary>
    Friend Shared ReadOnly Property Acct_DuplicateUser() As String
        Get
            Return ResourceManager.GetString("Acct_DuplicateUser", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to E-mail Address.
    '''</summary>
    Friend Shared ReadOnly Property Acct_EmailAddress() As String
        Get
            Return ResourceManager.GetString("Acct_EmailAddress", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to E-mail address changed and activation e-mail sent to reactivate account..
    '''</summary>
    Friend Shared ReadOnly Property Acct_EmailChangeReactivate() As String
        Get
            Return ResourceManager.GetString("Acct_EmailChangeReactivate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to E-mail already in use please login with existing credentials..
    '''</summary>
    Friend Shared ReadOnly Property Acct_EmailInUse() As String
        Get
            Return ResourceManager.GetString("Acct_EmailInUse", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to E-mail addresses do not match.
    '''</summary>
    Friend Shared ReadOnly Property Acct_EmailsNotMatch() As String
        Get
            Return ResourceManager.GetString("Acct_EmailsNotMatch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enable SSL.
    '''</summary>
    Friend Shared ReadOnly Property Acct_EnableSSL() As String
        Get
            Return ResourceManager.GetString("Acct_EnableSSL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Forgot Password.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ForgotPassword() As String
        Get
            Return ResourceManager.GetString("Acct_ForgotPassword", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Forgot Username.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ForgotUsername() As String
        Get
            Return ResourceManager.GetString("Acct_ForgotUsername", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Home.
    '''</summary>
    Friend Shared ReadOnly Property Acct_Home() As String
        Get
            Return ResourceManager.GetString("Acct_Home", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Incorrect activation code..
    '''</summary>
    Friend Shared ReadOnly Property Acct_IncorrectActivationCode() As String
        Get
            Return ResourceManager.GetString("Acct_IncorrectActivationCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Incorrect password reset code..
    '''</summary>
    Friend Shared ReadOnly Property Acct_IncorrectPasswordResetCode() As String
        Get
            Return ResourceManager.GetString("Acct_IncorrectPasswordResetCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid input..
    '''</summary>
    Friend Shared ReadOnly Property Acct_InvalidInput() As String
        Get
            Return ResourceManager.GetString("Acct_InvalidInput", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Invalid username or password..
    '''</summary>
    Friend Shared ReadOnly Property Acct_InvalidUsernamePassword() As String
        Get
            Return ResourceManager.GetString("Acct_InvalidUsernamePassword", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Login.
    '''</summary>
    Friend Shared ReadOnly Property Acct_Login() As String
        Get
            Return ResourceManager.GetString("Acct_Login", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Login successful..
    '''</summary>
    Friend Shared ReadOnly Property Acct_LoginSuccess() As String
        Get
            Return ResourceManager.GetString("Acct_LoginSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Logoff.
    '''</summary>
    Friend Shared ReadOnly Property Acct_Logoff() As String
        Get
            Return ResourceManager.GetString("Acct_Logoff", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Logoff successful..
    '''</summary>
    Friend Shared ReadOnly Property Acct_LogoffSuccess() As String
        Get
            Return ResourceManager.GetString("Acct_LogoffSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Password must be at least 8 characters..
    '''</summary>
    Friend Shared ReadOnly Property Acct_MinimumPassword() As String
        Get
            Return ResourceManager.GetString("Acct_MinimumPassword", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Username must be at least 4 characters..
    '''</summary>
    Friend Shared ReadOnly Property Acct_MinimumUsername() As String
        Get
            Return ResourceManager.GetString("Acct_MinimumUsername", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No.
    '''</summary>
    Friend Shared ReadOnly Property Acct_No() As String
        Get
            Return ResourceManager.GetString("Acct_No", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Must confirm account deletion..
    '''</summary>
    Friend Shared ReadOnly Property Acct_NotConfirmDelete() As String
        Get
            Return ResourceManager.GetString("Acct_NotConfirmDelete", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No user exists for the entered e-mail address..
    '''</summary>
    Friend Shared ReadOnly Property Acct_NoUserExists() As String
        Get
            Return ResourceManager.GetString("Acct_NoUserExists", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Password.
    '''</summary>
    Friend Shared ReadOnly Property Acct_Password() As String
        Get
            Return ResourceManager.GetString("Acct_Password", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Password already reset or process not initiated..
    '''</summary>
    Friend Shared ReadOnly Property Acct_PasswordAlreadyReset() As String
        Get
            Return ResourceManager.GetString("Acct_PasswordAlreadyReset", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This e-mail is to inform of the password change of your {0} account: {1}..
    '''</summary>
    Friend Shared ReadOnly Property Acct_PasswordChangedBody() As String
        Get
            Return ResourceManager.GetString("Acct_PasswordChangedBody", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Password changed for account at {0}.
    '''</summary>
    Friend Shared ReadOnly Property Acct_PasswordChangedSubject() As String
        Get
            Return ResourceManager.GetString("Acct_PasswordChangedSubject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Password successfully changed..
    '''</summary>
    Friend Shared ReadOnly Property Acct_PasswordChangeSuccess() As String
        Get
            Return ResourceManager.GetString("Acct_PasswordChangeSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to An e-mail has been sent to your address on file to initiate the password reset process..
    '''</summary>
    Friend Shared ReadOnly Property Acct_PasswordEmailSent() As String
        Get
            Return ResourceManager.GetString("Acct_PasswordEmailSent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This e-mail is to reset the password of your {0} account: {1}.  Please use the following link: {3} or by proceeding to the page {4}  and entering your username and the following password reset code: {5}.
    '''</summary>
    Friend Shared ReadOnly Property Acct_PasswordResetBody() As String
        Get
            Return ResourceManager.GetString("Acct_PasswordResetBody", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Password Reset Code.
    '''</summary>
    Friend Shared ReadOnly Property Acct_PasswordResetCode() As String
        Get
            Return ResourceManager.GetString("Acct_PasswordResetCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Password reset for account at {0}.
    '''</summary>
    Friend Shared ReadOnly Property Acct_PasswordResetSubject() As String
        Get
            Return ResourceManager.GetString("Acct_PasswordResetSubject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Password successfully reset..
    '''</summary>
    Friend Shared ReadOnly Property Acct_PasswordResetSuccess() As String
        Get
            Return ResourceManager.GetString("Acct_PasswordResetSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Passwords do not match.
    '''</summary>
    Friend Shared ReadOnly Property Acct_PasswordsNotMatch() As String
        Get
            Return ResourceManager.GetString("Acct_PasswordsNotMatch", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Private Key.
    '''</summary>
    Friend Shared ReadOnly Property Acct_PrivateKey() As String
        Get
            Return ResourceManager.GetString("Acct_PrivateKey", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Register.
    '''</summary>
    Friend Shared ReadOnly Property Acct_Register() As String
        Get
            Return ResourceManager.GetString("Acct_Register", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Remember?.
    '''</summary>
    Friend Shared ReadOnly Property Acct_Remember() As String
        Get
            Return ResourceManager.GetString("Acct_Remember", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Remove Database.
    '''</summary>
    Friend Shared ReadOnly Property Acct_RemoveDatabase() As String
        Get
            Return ResourceManager.GetString("Acct_RemoveDatabase", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Resend Activation E-mail.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ResendActivationEmail() As String
        Get
            Return ResourceManager.GetString("Acct_ResendActivationEmail", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Reset Password.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ResetPassword() As String
        Get
            Return ResourceManager.GetString("Acct_ResetPassword", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Retrieve Password.
    '''</summary>
    Friend Shared ReadOnly Property Acct_RetrievePassword() As String
        Get
            Return ResourceManager.GetString("Acct_RetrievePassword", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Retrieve Username.
    '''</summary>
    Friend Shared ReadOnly Property Acct_RetrieveUsername() As String
        Get
            Return ResourceManager.GetString("Acct_RetrieveUsername", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Send Activation Code.
    '''</summary>
    Friend Shared ReadOnly Property Acct_SendActivationCode() As String
        Get
            Return ResourceManager.GetString("Acct_SendActivationCode", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Username.
    '''</summary>
    Friend Shared ReadOnly Property Acct_Username() As String
        Get
            Return ResourceManager.GetString("Acct_Username", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This e-mail is to inform of the account name change of your {0} account: {1}..
    '''</summary>
    Friend Shared ReadOnly Property Acct_UsernameChangedBody() As String
        Get
            Return ResourceManager.GetString("Acct_UsernameChangedBody", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Username changed for account at {0}.
    '''</summary>
    Friend Shared ReadOnly Property Acct_UsernameChangedSubject() As String
        Get
            Return ResourceManager.GetString("Acct_UsernameChangedSubject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Username successfully changed..
    '''</summary>
    Friend Shared ReadOnly Property Acct_UsernameChangeSuccess() As String
        Get
            Return ResourceManager.GetString("Acct_UsernameChangeSuccess", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to An e-mail has been sent to your address on file with your username..
    '''</summary>
    Friend Shared ReadOnly Property Acct_UsernameEmailSent() As String
        Get
            Return ResourceManager.GetString("Acct_UsernameEmailSent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to This e-mail is a reminder of your {0} account: {1}..
    '''</summary>
    Friend Shared ReadOnly Property Acct_UsernameReminderBody() As String
        Get
            Return ResourceManager.GetString("Acct_UsernameReminderBody", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Username reminder for account at {0}.
    '''</summary>
    Friend Shared ReadOnly Property Acct_UsernameReminderSubject() As String
        Get
            Return ResourceManager.GetString("Acct_UsernameReminderSubject", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to User does not exist..
    '''</summary>
    Friend Shared ReadOnly Property Acct_UserNotFound() As String
        Get
            Return ResourceManager.GetString("Acct_UserNotFound", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View Cache.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ViewCache() As String
        Get
            Return ResourceManager.GetString("Acct_ViewCache", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View Certificate Requests.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ViewCertRequests() As String
        Get
            Return ResourceManager.GetString("Acct_ViewCertRequests", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View Disk Cache.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ViewDiskCache() As String
        Get
            Return ResourceManager.GetString("Acct_ViewDiskCache", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View Headers.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ViewHeaders() As String
        Get
            Return ResourceManager.GetString("Acct_ViewHeaders", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to View Sites.
    '''</summary>
    Friend Shared ReadOnly Property Acct_ViewSites() As String
        Get
            Return ResourceManager.GetString("Acct_ViewSites", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Yes.
    '''</summary>
    Friend Shared ReadOnly Property Acct_Yes() As String
        Get
            Return ResourceManager.GetString("Acct_Yes", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ኣማርኛ.
    '''</summary>
    Friend Shared ReadOnly Property lang_am() As String
        Get
            Return ResourceManager.GetString("lang_am", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to العربية.
    '''</summary>
    Friend Shared ReadOnly Property lang_ar() As String
        Get
            Return ResourceManager.GetString("lang_ar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Azərbaycan dili.
    '''</summary>
    Friend Shared ReadOnly Property lang_az() As String
        Get
            Return ResourceManager.GetString("lang_az", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tamazight.
    '''</summary>
    Friend Shared ReadOnly Property lang_ber() As String
        Get
            Return ResourceManager.GetString("lang_ber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to български.
    '''</summary>
    Friend Shared ReadOnly Property lang_bg() As String
        Get
            Return ResourceManager.GetString("lang_bg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to বাংলা.
    '''</summary>
    Friend Shared ReadOnly Property lang_bn() As String
        Get
            Return ResourceManager.GetString("lang_bn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to bosanski.
    '''</summary>
    Friend Shared ReadOnly Property lang_bs() As String
        Get
            Return ResourceManager.GetString("lang_bs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to čeština.
    '''</summary>
    Friend Shared ReadOnly Property lang_cs() As String
        Get
            Return ResourceManager.GetString("lang_cs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Deutsch.
    '''</summary>
    Friend Shared ReadOnly Property lang_de() As String
        Get
            Return ResourceManager.GetString("lang_de", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ދިވެހި.
    '''</summary>
    Friend Shared ReadOnly Property lang_dv() As String
        Get
            Return ResourceManager.GetString("lang_dv", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to English.
    '''</summary>
    Friend Shared ReadOnly Property lang_en() As String
        Get
            Return ResourceManager.GetString("lang_en", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to español.
    '''</summary>
    Friend Shared ReadOnly Property lang_es() As String
        Get
            Return ResourceManager.GetString("lang_es", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to فارسى.
    '''</summary>
    Friend Shared ReadOnly Property lang_fa() As String
        Get
            Return ResourceManager.GetString("lang_fa", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to français.
    '''</summary>
    Friend Shared ReadOnly Property lang_fr() As String
        Get
            Return ResourceManager.GetString("lang_fr", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ḥawsa.
    '''</summary>
    Friend Shared ReadOnly Property lang_ha() As String
        Get
            Return ResourceManager.GetString("lang_ha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to हिन्दी.
    '''</summary>
    Friend Shared ReadOnly Property lang_hi() As String
        Get
            Return ResourceManager.GetString("lang_hi", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bahasa Indonesia.
    '''</summary>
    Friend Shared ReadOnly Property lang_id() As String
        Get
            Return ResourceManager.GetString("lang_id", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to italiano.
    '''</summary>
    Friend Shared ReadOnly Property lang_it() As String
        Get
            Return ResourceManager.GetString("lang_it", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 日本語.
    '''</summary>
    Friend Shared ReadOnly Property lang_ja() As String
        Get
            Return ResourceManager.GetString("lang_ja", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 한국어.
    '''</summary>
    Friend Shared ReadOnly Property lang_ko() As String
        Get
            Return ResourceManager.GetString("lang_ko", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to کوردی.
    '''</summary>
    Friend Shared ReadOnly Property lang_ku() As String
        Get
            Return ResourceManager.GetString("lang_ku", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amharic.
    '''</summary>
    Friend Shared ReadOnly Property lang_localam() As String
        Get
            Return ResourceManager.GetString("lang_localam", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic.
    '''</summary>
    Friend Shared ReadOnly Property lang_localar() As String
        Get
            Return ResourceManager.GetString("lang_localar", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Azerbaijani.
    '''</summary>
    Friend Shared ReadOnly Property lang_localaz() As String
        Get
            Return ResourceManager.GetString("lang_localaz", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Amazigh.
    '''</summary>
    Friend Shared ReadOnly Property lang_localber() As String
        Get
            Return ResourceManager.GetString("lang_localber", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bulgarian.
    '''</summary>
    Friend Shared ReadOnly Property lang_localbg() As String
        Get
            Return ResourceManager.GetString("lang_localbg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bengali.
    '''</summary>
    Friend Shared ReadOnly Property lang_localbn() As String
        Get
            Return ResourceManager.GetString("lang_localbn", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bosnian.
    '''</summary>
    Friend Shared ReadOnly Property lang_localbs() As String
        Get
            Return ResourceManager.GetString("lang_localbs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Czech.
    '''</summary>
    Friend Shared ReadOnly Property lang_localcs() As String
        Get
            Return ResourceManager.GetString("lang_localcs", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to German.
    '''</summary>
    Friend Shared ReadOnly Property lang_localde() As String
        Get
            Return ResourceManager.GetString("lang_localde", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Divehi.
    '''</summary>
    Friend Shared ReadOnly Property lang_localdv() As String
        Get
            Return ResourceManager.GetString("lang_localdv", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to English.
    '''</summary>
    Friend Shared ReadOnly Property lang_localen() As String
        Get
            Return ResourceManager.GetString("lang_localen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Spanish.
    '''</summary>
    Friend Shared ReadOnly Property lang_locales() As String
        Get
            Return ResourceManager.GetString("lang_locales", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Persian.
    '''</summary>
    Friend Shared ReadOnly Property lang_localfa() As String
        Get
            Return ResourceManager.GetString("lang_localfa", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to French.
    '''</summary>
    Friend Shared ReadOnly Property lang_localfr() As String
        Get
            Return ResourceManager.GetString("lang_localfr", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hausa.
    '''</summary>
    Friend Shared ReadOnly Property lang_localha() As String
        Get
            Return ResourceManager.GetString("lang_localha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hindi.
    '''</summary>
    Friend Shared ReadOnly Property lang_localhi() As String
        Get
            Return ResourceManager.GetString("lang_localhi", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Indonesian.
    '''</summary>
    Friend Shared ReadOnly Property lang_localid() As String
        Get
            Return ResourceManager.GetString("lang_localid", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Italian.
    '''</summary>
    Friend Shared ReadOnly Property lang_localit() As String
        Get
            Return ResourceManager.GetString("lang_localit", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Japanese.
    '''</summary>
    Friend Shared ReadOnly Property lang_localja() As String
        Get
            Return ResourceManager.GetString("lang_localja", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Korean.
    '''</summary>
    Friend Shared ReadOnly Property lang_localko() As String
        Get
            Return ResourceManager.GetString("lang_localko", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kurdish.
    '''</summary>
    Friend Shared ReadOnly Property lang_localku() As String
        Get
            Return ResourceManager.GetString("lang_localku", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Malayalam.
    '''</summary>
    Friend Shared ReadOnly Property lang_localml() As String
        Get
            Return ResourceManager.GetString("lang_localml", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Malay.
    '''</summary>
    Friend Shared ReadOnly Property lang_localms() As String
        Get
            Return ResourceManager.GetString("lang_localms", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Dutch.
    '''</summary>
    Friend Shared ReadOnly Property lang_localnl() As String
        Get
            Return ResourceManager.GetString("lang_localnl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Norwegian.
    '''</summary>
    Friend Shared ReadOnly Property lang_localno() As String
        Get
            Return ResourceManager.GetString("lang_localno", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Polish.
    '''</summary>
    Friend Shared ReadOnly Property lang_localpl() As String
        Get
            Return ResourceManager.GetString("lang_localpl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Portuguese.
    '''</summary>
    Friend Shared ReadOnly Property lang_localpt() As String
        Get
            Return ResourceManager.GetString("lang_localpt", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Romanian.
    '''</summary>
    Friend Shared ReadOnly Property lang_localro() As String
        Get
            Return ResourceManager.GetString("lang_localro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Russian.
    '''</summary>
    Friend Shared ReadOnly Property lang_localru() As String
        Get
            Return ResourceManager.GetString("lang_localru", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Sindhi.
    '''</summary>
    Friend Shared ReadOnly Property lang_localsd() As String
        Get
            Return ResourceManager.GetString("lang_localsd", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Somali.
    '''</summary>
    Friend Shared ReadOnly Property lang_localso() As String
        Get
            Return ResourceManager.GetString("lang_localso", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Albanian.
    '''</summary>
    Friend Shared ReadOnly Property lang_localsq() As String
        Get
            Return ResourceManager.GetString("lang_localsq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Swedish.
    '''</summary>
    Friend Shared ReadOnly Property lang_localsv() As String
        Get
            Return ResourceManager.GetString("lang_localsv", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Swahili.
    '''</summary>
    Friend Shared ReadOnly Property lang_localsw() As String
        Get
            Return ResourceManager.GetString("lang_localsw", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tamil.
    '''</summary>
    Friend Shared ReadOnly Property lang_localta() As String
        Get
            Return ResourceManager.GetString("lang_localta", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tajik.
    '''</summary>
    Friend Shared ReadOnly Property lang_localtg() As String
        Get
            Return ResourceManager.GetString("lang_localtg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Thai.
    '''</summary>
    Friend Shared ReadOnly Property lang_localth() As String
        Get
            Return ResourceManager.GetString("lang_localth", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Turkish.
    '''</summary>
    Friend Shared ReadOnly Property lang_localtr() As String
        Get
            Return ResourceManager.GetString("lang_localtr", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Tatar.
    '''</summary>
    Friend Shared ReadOnly Property lang_localtt() As String
        Get
            Return ResourceManager.GetString("lang_localtt", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Uyghur.
    '''</summary>
    Friend Shared ReadOnly Property lang_localug() As String
        Get
            Return ResourceManager.GetString("lang_localug", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Urdu.
    '''</summary>
    Friend Shared ReadOnly Property lang_localur() As String
        Get
            Return ResourceManager.GetString("lang_localur", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Uzbek.
    '''</summary>
    Friend Shared ReadOnly Property lang_localuz() As String
        Get
            Return ResourceManager.GetString("lang_localuz", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chinese.
    '''</summary>
    Friend Shared ReadOnly Property lang_localzh() As String
        Get
            Return ResourceManager.GetString("lang_localzh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to മലയാളം.
    '''</summary>
    Friend Shared ReadOnly Property lang_ml() As String
        Get
            Return ResourceManager.GetString("lang_ml", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bahasa melayu.
    '''</summary>
    Friend Shared ReadOnly Property lang_ms() As String
        Get
            Return ResourceManager.GetString("lang_ms", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Nederlands.
    '''</summary>
    Friend Shared ReadOnly Property lang_nl() As String
        Get
            Return ResourceManager.GetString("lang_nl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Norsk.
    '''</summary>
    Friend Shared ReadOnly Property lang_no() As String
        Get
            Return ResourceManager.GetString("lang_no", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to polski.
    '''</summary>
    Friend Shared ReadOnly Property lang_pl() As String
        Get
            Return ResourceManager.GetString("lang_pl", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to português.
    '''</summary>
    Friend Shared ReadOnly Property lang_pt() As String
        Get
            Return ResourceManager.GetString("lang_pt", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to रोमानो.
    '''</summary>
    Friend Shared ReadOnly Property lang_ro() As String
        Get
            Return ResourceManager.GetString("lang_ro", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Русский язык.
    '''</summary>
    Friend Shared ReadOnly Property lang_ru() As String
        Get
            Return ResourceManager.GetString("lang_ru", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to سنڌي.
    '''</summary>
    Friend Shared ReadOnly Property lang_sd() As String
        Get
            Return ResourceManager.GetString("lang_sd", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to af Soomaali.
    '''</summary>
    Friend Shared ReadOnly Property lang_so() As String
        Get
            Return ResourceManager.GetString("lang_so", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to shqip.
    '''</summary>
    Friend Shared ReadOnly Property lang_sq() As String
        Get
            Return ResourceManager.GetString("lang_sq", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Svenska.
    '''</summary>
    Friend Shared ReadOnly Property lang_sv() As String
        Get
            Return ResourceManager.GetString("lang_sv", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Kiswahili.
    '''</summary>
    Friend Shared ReadOnly Property lang_sw() As String
        Get
            Return ResourceManager.GetString("lang_sw", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to தமிழ்.
    '''</summary>
    Friend Shared ReadOnly Property lang_ta() As String
        Get
            Return ResourceManager.GetString("lang_ta", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to тоҷики.
    '''</summary>
    Friend Shared ReadOnly Property lang_tg() As String
        Get
            Return ResourceManager.GetString("lang_tg", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ภาษาไทย.
    '''</summary>
    Friend Shared ReadOnly Property lang_th() As String
        Get
            Return ResourceManager.GetString("lang_th", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Türkçe.
    '''</summary>
    Friend Shared ReadOnly Property lang_tr() As String
        Get
            Return ResourceManager.GetString("lang_tr", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to татарча.
    '''</summary>
    Friend Shared ReadOnly Property lang_tt() As String
        Get
            Return ResourceManager.GetString("lang_tt", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to ئۇيغۇر.
    '''</summary>
    Friend Shared ReadOnly Property lang_ug() As String
        Get
            Return ResourceManager.GetString("lang_ug", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to اردو.
    '''</summary>
    Friend Shared ReadOnly Property lang_ur() As String
        Get
            Return ResourceManager.GetString("lang_ur", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to o&apos;zbek tili ўзбек тили.
    '''</summary>
    Friend Shared ReadOnly Property lang_uz() As String
        Get
            Return ResourceManager.GetString("lang_uz", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 中文.
    '''</summary>
    Friend Shared ReadOnly Property lang_zh() As String
        Get
            Return ResourceManager.GetString("lang_zh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Comma.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicComma() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicComma", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Damma.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicDamma() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicDamma", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Dammatan.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicDammatan() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicDammatan", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Empty Centre High Stop.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicEmptyCentreHighStop() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicEmptyCentreHighStop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Empty Centre Low Stop.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicEmptyCentreLowStop() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicEmptyCentreLowStop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic End Of Ayah.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicEndOfAyah() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicEndOfAyah", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Fatha.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicFatha() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicFatha", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Fathatan.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicFathatan() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicFathatan", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Hamza Above.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicHamzaAbove() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicHamzaAbove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Hamza Below.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicHamzaBelow() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicHamzaBelow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic-Indic Digit Eight.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicIndicDigitEight() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicIndicDigitEight", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic-Indic Digit Five.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicIndicDigitFive() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicIndicDigitFive", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic-Indic Digit Four.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicIndicDigitFour() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicIndicDigitFour", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic-Indic Digit Nine.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicIndicDigitNine() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicIndicDigitNine", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic-Indic Digit One.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicIndicDigitOne() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicIndicDigitOne", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic-Indic Digit Seven.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicIndicDigitSeven() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicIndicDigitSeven", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic-Indic Digit Six.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicIndicDigitSix() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicIndicDigitSix", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic-Indic Digit Three.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicIndicDigitThree() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicIndicDigitThree", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic-Indic Digit Two.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicIndicDigitTwo() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicIndicDigitTwo", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic-Indic Digit Zero.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicIndicDigitZero() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicIndicDigitZero", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Kasra.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicKasra() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicKasra", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Kasratan.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicKasratan() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicKasratan", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Ain.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterAin() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterAin", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Alef.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterAlef() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterAlef", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Alef Maksura.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterAlefMaksura() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterAlefMaksura", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Alef Wasla.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterAlefWasla() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterAlefWasla", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Alef With Hamza Above.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterAlefWithHamzaAbove() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterAlefWithHamzaAbove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Alef With Hamza Below.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterAlefWithHamzaBelow() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterAlefWithHamzaBelow", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Alef With Madda Above.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterAlefWithMaddaAbove() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterAlefWithMaddaAbove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Beh.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterBeh() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterBeh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Dad.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterDad() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterDad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Dal.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterDal() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterDal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Feh.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterFeh() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterFeh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Gaf.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterGaf() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterGaf", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Ghain.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterGhain() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterGhain", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Hah.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterHah() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterHah", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Hamza.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterHamza() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterHamza", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Heh.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterHeh() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterHeh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Jeem.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterJeem() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterJeem", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Kaf.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterKaf() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterKaf", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Khah.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterKhah() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterKhah", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Lam.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterLam() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterLam", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Meem.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterMeem() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterMeem", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Noon.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterNoon() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterNoon", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Peh.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterPeh() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterPeh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Qaf.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterQaf() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterQaf", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Reh.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterReh() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterReh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Sad.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterSad() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterSad", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Seen.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterSeen() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterSeen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Sheen.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterSheen() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterSheen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Superscript Alef.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterSuperscriptAlef() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterSuperscriptAlef", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Tah.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterTah() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterTah", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Tcheh.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterTcheh() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterTcheh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Teh.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterTeh() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterTeh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Teh Marbuta.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterTehMarbuta() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterTehMarbuta", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Thal.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterThal() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterThal", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Theh.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterTheh() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterTheh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Veh.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterVeh() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterVeh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Waw.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterWaw() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterWaw", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Waw With Hamza Above.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterWawWithHamzaAbove() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterWawWithHamzaAbove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Yeh.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterYeh() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterYeh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Yeh With Hamza Above.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterYehWithHamzaAbove() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterYehWithHamzaAbove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Zah.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterZah() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterZah", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Letter Zain.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLetterZain() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLetterZain", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Akbar Isolated Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureAkbarIsolatedForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureAkbarIsolatedForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Alayhe Isolated Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureAlayheIsolatedForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureAlayheIsolatedForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Allah Isolated Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureAllahIsolatedForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureAllahIsolatedForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Bismillah Ar-Rahman Ar-Raheem.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureBismillahArRahmanArRaheem() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureBismillahArRahmanArRaheem", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Jallajalalouhou.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureJallajalalouhou() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureJallajalalouhou", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Mohammad Isolated Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureMohammadIsolatedForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureMohammadIsolatedForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Qala Used As Koranic Stop Sign Isolated Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureQalaUsedAsKoranicStopSignIsolatedForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureQalaUsedAsKoranicStopSignIsolatedForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Rasoul Isolated Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureRasoulIsolatedForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureRasoulIsolatedForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Salam Isolated Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureSalamIsolatedForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureSalamIsolatedForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Salla Isolated Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureSallaIsolatedForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureSallaIsolatedForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Sallallahou Alayhe Wasallam.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureSallallahouAlayheWasallam() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureSallallahouAlayheWasallam", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Salla Used As Koranic Stop Sign Isolated Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureSallaUsedAsKoranicStopSignIsolatedForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureSallaUsedAsKoranicStopSignIsolatedForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Ligature Wasallam Isolated Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicLigatureWasallamIsolatedForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicLigatureWasallamIsolatedForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Maddah Above.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicMaddahAbove() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicMaddahAbove", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Place Of Sajdah.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicPlaceOfSajdah() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicPlaceOfSajdah", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Question Mark.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicQuestionMark() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicQuestionMark", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Rounded High Stop With Filled Centre.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicRoundedHighStopWithFilledCentre() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicRoundedHighStopWithFilledCentre", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Semicolon.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSemicolon() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSemicolon", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Shadda.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicShadda() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicShadda", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small High Jeem.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallHighJeem() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallHighJeem", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small High Lam Alef.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallHighLamAlef() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallHighLamAlef", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small High Ligature Qaf With Lam With Alef Maksura.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallHighLigatureQafWithLamWithAlefMaksura() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallHighLigatureQafWithLamWithAlefMaksura", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small High Ligature Sad With Lam With Alef Maksura.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallHighLigatureSadWithLamWithAlefMaksura() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallHighLigatureSadWithLamWithAlefMaksura", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small High Meem Initial Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallHighMeemInitialForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallHighMeemInitialForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small High Meem Isolated Form.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallHighMeemIsolatedForm() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallHighMeemIsolatedForm", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small High Noon.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallHighNoon() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallHighNoon", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small High Rounded Zero.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallHighRoundedZero() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallHighRoundedZero", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small High Seen.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallHighSeen() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallHighSeen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small High Three Dots.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallHighThreeDots() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallHighThreeDots", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small High Upright Rectangular Zero.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallHighUprightRectangularZero() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallHighUprightRectangularZero", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small Low Meem.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallLowMeem() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallLowMeem", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small Low Seen.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallLowSeen() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallLowSeen", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small Waw.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallWaw() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallWaw", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Small Yeh.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSmallYeh() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSmallYeh", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Start Of Rub El Hizb.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicStartOfRubElHizb() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicStartOfRubElHizb", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Sukun.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicSukun() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicSukun", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Arabic Tatweel.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ArabicTatweel() As String
        Get
            Return ResourceManager.GetString("unicode_ArabicTatweel", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Colon.
    '''</summary>
    Friend Shared ReadOnly Property unicode_Colon() As String
        Get
            Return ResourceManager.GetString("unicode_Colon", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Comma.
    '''</summary>
    Friend Shared ReadOnly Property unicode_Comma() As String
        Get
            Return ResourceManager.GetString("unicode_Comma", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Exclamation Mark.
    '''</summary>
    Friend Shared ReadOnly Property unicode_ExclamationMark() As String
        Get
            Return ResourceManager.GetString("unicode_ExclamationMark", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Full Stop.
    '''</summary>
    Friend Shared ReadOnly Property unicode_FullStop() As String
        Get
            Return ResourceManager.GetString("unicode_FullStop", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hyphen-Minus.
    '''</summary>
    Friend Shared ReadOnly Property unicode_HyphenMinus() As String
        Get
            Return ResourceManager.GetString("unicode_HyphenMinus", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Left Curly Bracket.
    '''</summary>
    Friend Shared ReadOnly Property unicode_LeftCurlyBracket() As String
        Get
            Return ResourceManager.GetString("unicode_LeftCurlyBracket", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Left-Pointing Double Angle Quotation Mark.
    '''</summary>
    Friend Shared ReadOnly Property unicode_LeftPointingDoubleAngleQuotationMark() As String
        Get
            Return ResourceManager.GetString("unicode_LeftPointingDoubleAngleQuotationMark", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Left Square Bracket.
    '''</summary>
    Friend Shared ReadOnly Property unicode_LeftSquareBracket() As String
        Get
            Return ResourceManager.GetString("unicode_LeftSquareBracket", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Left-To-Right Embedding.
    '''</summary>
    Friend Shared ReadOnly Property unicode_LeftToRightEmbedding() As String
        Get
            Return ResourceManager.GetString("unicode_LeftToRightEmbedding", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Left-To-Right Mark.
    '''</summary>
    Friend Shared ReadOnly Property unicode_LeftToRightMark() As String
        Get
            Return ResourceManager.GetString("unicode_LeftToRightMark", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Left-To-Right Override.
    '''</summary>
    Friend Shared ReadOnly Property unicode_LeftToRightOverride() As String
        Get
            Return ResourceManager.GetString("unicode_LeftToRightOverride", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ornate Left Parenthesis.
    '''</summary>
    Friend Shared ReadOnly Property unicode_OrnateLeftParenthesis() As String
        Get
            Return ResourceManager.GetString("unicode_OrnateLeftParenthesis", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Ornate Right Parenthesis.
    '''</summary>
    Friend Shared ReadOnly Property unicode_OrnateRightParenthesis() As String
        Get
            Return ResourceManager.GetString("unicode_OrnateRightParenthesis", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Pop Directional Formatting.
    '''</summary>
    Friend Shared ReadOnly Property unicode_PopDirectionalFormatting() As String
        Get
            Return ResourceManager.GetString("unicode_PopDirectionalFormatting", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Quotation Mark.
    '''</summary>
    Friend Shared ReadOnly Property unicode_QuotationMark() As String
        Get
            Return ResourceManager.GetString("unicode_QuotationMark", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Rial Sign.
    '''</summary>
    Friend Shared ReadOnly Property unicode_RialSign() As String
        Get
            Return ResourceManager.GetString("unicode_RialSign", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Right Curly Bracket.
    '''</summary>
    Friend Shared ReadOnly Property unicode_RightCurlyBracket() As String
        Get
            Return ResourceManager.GetString("unicode_RightCurlyBracket", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Right-Pointing Double Angle Quotation Mark.
    '''</summary>
    Friend Shared ReadOnly Property unicode_RightPointingDoubleAngleQuotationMark() As String
        Get
            Return ResourceManager.GetString("unicode_RightPointingDoubleAngleQuotationMark", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Right Square Bracket.
    '''</summary>
    Friend Shared ReadOnly Property unicode_RightSquareBracket() As String
        Get
            Return ResourceManager.GetString("unicode_RightSquareBracket", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Right-To-Left Embedding.
    '''</summary>
    Friend Shared ReadOnly Property unicode_RightToLeftEmbedding() As String
        Get
            Return ResourceManager.GetString("unicode_RightToLeftEmbedding", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Right-To-Left Mark.
    '''</summary>
    Friend Shared ReadOnly Property unicode_RightToLeftMark() As String
        Get
            Return ResourceManager.GetString("unicode_RightToLeftMark", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Right-To-Left Override.
    '''</summary>
    Friend Shared ReadOnly Property unicode_RightToLeftOverride() As String
        Get
            Return ResourceManager.GetString("unicode_RightToLeftOverride", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Space.
    '''</summary>
    Friend Shared ReadOnly Property unicode_Space() As String
        Get
            Return ResourceManager.GetString("unicode_Space", resourceCulture)
        End Get
    End Property
End Class
